### ISSUE TITLE
Unable to list topics after upgrading from v1.3.0 to v1.4.2

### ISSUE THREAD

**Issue by prasadkris** [kafbat/kafka-ui#1512]
### Issue submitter TODO list

- [x] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [x] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [x] I've tried running `main`-labeled docker image and the issue still persists there
- [x] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

We have a Kafka UI deployment running inside our K8s cluster and it has been working like a charm. Yesterday we upgraded from version **v1.3.0 to v1.4.2,** and that update seems to have broken the setup, I’m unable to view the topic list for our clusters (other items like brokers, etc. still work fine). I just get a spinning wheel when I try to view the topic list. After reverting back to version **v1.3.0,** it started working fine again.

### Expected behavior

The topic list should load correctly after the upgrade.

### Your installation details

appVersion: v1.4.2
helm chart version: 1.5.3

helm `values.yaml`

```
image:
  registry: ghcr.io
  repository: kafbat/kafka-ui
  pullPolicy: IfNotPresent

yamlApplicationConfig:
  kafka:
    clusters:
      - name: xxxxxx
        bootstrapServers: kafka:9092
        schemaRegistry: http://avro-schema-registry:8081
        readOnly: false
      - name: xxxxxx
        bootstrapServers: xxxxxxx.svc.cluster.local:9092
      - name: xxxxxxxx
        bootstrapServers: xxxxxxxxxxx.svc.cluster.local:9092

  auth:
    type: OAUTH2
    oauth2:
      client:
        keycloak:
          clientId: kafka-ui
          clientSecret: xxxxxxxxxxxxxxxx
          scope: openid
          issuer-uri: xxxxxxxxxxxxxxxxxx
          user-name-attribute: preferred_username
          client-name: kafka-ui
          provider: keycloak
          custom-params:
           type: keycloak
  management:
    health:
      ldap:
        enabled: false
envs:
  config:
    LOGGING_LEVEL_IO_KAFBAT_UI: error
    LOGGING_LEVEL_ROOT: error

# Ingress configuration
ingress:
  enabled: true
  path: "/"
  pathType: "Prefix"  
  host: "kafka-ui.xxxxxxx.dev"
  tls:
    enabled: false

resources: {}
````

### Steps to reproduce

1. Deploy kafka-ui version v1.3.0 on K8s and verify that the topic list loads correctly.
2. Upgrade kafka-ui from v1.3.0 to v1.4.2.
3. Open the kafka UI in the browser.
4. Go to **Cluster → Topics** for any configured cluster.
5. Observe that the topic list does not load and only a spinning loader is shown.

**Comment by Haarolean** [comment]
Please share whatever there is in browser dev console

**Comment by prasadkris** [comment]
Thanks 🙏🏻  unfortunately I get nothing in the console, just a spinning wheel with no data in the dev console.

<img width="1648" height="877" alt="Image" src="https://github.com/user-attachments/assets/59ad82cf-3e72-45ca-b4d1-59a0ebf87c5a" />

The debug logs captured during this issue are [here](https://gist.github.com/prasadkris/386f74d44b1722f1c3606cb7e3ff4b84) if you’d like to have a look.

**Comment by germanosin** [comment]
@prasadkris could you please
1. share network tab queries and there results/body in the browser. 
2. Try to query api directly `/api/clusters/{clusterName}/topics`
3. Check rbac and acl
4. Check error logs before queries (might be problem with metadata collection)

**Comment by prasadkris** [comment]
Thank you @germanosin! 🙏🏻 The topic list just goes into an endless spinning wheel, with no progress in the Network tab’s Queries section. The only issue is with the topics list; other details like info, broker list, etc. are displaying fine

<img width="1676" height="893" alt="Image" src="https://github.com/user-attachments/assets/564f611b-421e-44d1-86e9-d7c132585538" />

I tried using a curl command to list the topics, but that also just hangs, whereas cluster info, cluster list, etc. are loading fine.  Please find the logs at:  https://gist.github.com/prasadkris/bbf90aaeaef2c2d50061b3bd6eab3f01 

Version 1.3.0 works without any issues, so I’ve reverted back to that version for now. We use OAuth2 (keycloak) logins, and I’ve checked for any errors in the logs, but everything looks normal, Thanks!

**Comment by zafodB** [comment]
We are having the exact same issue, also recently upgraded to 1.4.2.

**Comment by enrico-rabeneck** [comment]
We have the same issue. The reason is, that one or more cluster are not available. Which leads to the effect, that no cluster is usable. When removing all "broken" clusters the service should work again. But still, its a bug. It should be possible to have clusters down for some time.

**Comment by Haarolean** [comment]
@zafodB @enrico-rabeneck these comments are not helpful. If you're also affected by the issue please upvote the issue first. Next, please provide the debugging info requested by German above.

**Comment by samuelburnett** [comment]
I ran into the same issue using the latest version of kafka-ui (1.4.2). I have no issue when I revert to v1.3.0. I am currently unable to provide the info for 1 and 2 from @germanosin comment, but I can for 3 and 4:

> **_3. Check rbac and acl_**

My Kafka cluster does not enforce any authentication/authorization.

> **_4. Check error logs before queries (might be problem with metadata collection)_**

```
Unexpected error while getting configs for brokers [1]

org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: describeConfigs

Disconnecting from node 1 due to socket connection setup timeout. The timeout value is 30000 ms.
```

My Kafka cluster consists of 3 brokers and 3 broker/controller nodes. I am running kafka-ui in docker using a compose file and environment variables. I can try to update this thread when I am able to gather the other information.

**Comment by mohmaniac** [comment]
> I ran into the same issue using the latest version of kafka-ui (1.4.2). I have no issue when I revert to v1.3.0. I am currently unable to provide the info for 1 and 2 from [@germanosin](https://github.com/germanosin) comment, but I can for 3 and 4:
> 
> > **_3. Check rbac and acl_**
> 
> My Kafka cluster does not enforce any authentication/authorization.
> 
> > **_4. Check error logs before queries (might be problem with metadata collection)_**
> 
> ```
> Unexpected error while getting configs for brokers [1]
> 
> org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: describeConfigs
> 
> Disconnecting from node 1 due to socket connection setup timeout. The timeout value is 30000 ms.
> ```
> 
> My Kafka cluster consists of 3 brokers and 3 broker/controller nodes. I am running kafka-ui in docker using a compose file and environment variables. I can try to update this thread when I am able to gather the other information.

Same here. Seems that a new permission is needed to get kafbat to work - that wasn't the case with 1.3.0 and earlier.

**Comment by prasadkris** [comment]
Any update on this? Thanks!

**Comment by mohmaniac** [comment]
Maybe #1672 and its proposed PR will restore the expected behaviour.

**Comment by Haarolean** [comment]
> Maybe [#1672](https://github.com/kafbat/kafka-ui/issues/1672) and its proposed PR will restore the expected behaviour.

nope, #1586 is a part of 1.5 and unreleased yet

**Comment by Haarolean** [comment]
Should be fixed in #1698

**Comment by Haarolean** [comment]
Should be fixed now in main, please report back if it's not

**Comment by prasadkris** [comment]
Hey @Haarolean I have upgraded to v1.5.0 today, but the issue persists. I only see a spinning wheel when I navigate to topics. The logs don't reveal any errors and no errors in the browser developer tab as well. Again reverted back to v1.3.0 and it works pretty well.

<img width="1533" height="835" alt="Image" src="https://github.com/user-attachments/assets/469812be-5336-4874-9805-233c019773a8" />

Let me know if you any further details, Thanks! 🙏🏻

**Comment by Haarolean** [comment]
> Hey @Haarolean I have upgraded to v1.5.0 today, but the issue persists. I only see a spinning wheel when I navigate to topics. The logs don't reveal any errors and no errors in the browser developer tab as well. Again reverted back to v1.3.0 and it works pretty well.
> 
> <img width="1533" height="835" alt="Image" src="https://github.com/user-attachments/assets/469812be-5336-4874-9805-233c019773a8" />
> 
> Let me know if you any further details, Thanks! 🙏🏻 

any browser's console errors are observed? does k-ui report successful metrics collection? are any acls set on the cluster?

**Comment by Haarolean** [comment]
can someone affected try this branch? https://github.com/kafbat/kafka-ui/pull/1837

**Comment by prasadkris** [comment]
hey @Haarolean Thanks, I built an image from this branch (image: prasadzone/kafka-ui:pr-1837-test), but the issue persists. It just hangs at the topic screen with a spinning wheel and no errors in the developer console. The old version v1.3.x works perfectly well.

<img width="1672" height="772" alt="Image" src="https://github.com/user-attachments/assets/23aba982-ad0f-447d-a628-23f3dda9432f" />

Please let me know if you need any further information's, Thanks! 🙏🏻
